### ISSUE TITLE
权限相关的配置

### ISSUE THREAD

**Issue by sunshine17123** [mtianyan/django-antd-tyadmin#11]
新建了非超级管理员用户，配置view，add, change 权限后，仍然可以执行删除用户的操作，大佬求解

**Comment by mtianyan** [comment]
抱歉哈，这个功能还没支持，目前只是帮你把权限能增删改查展示，还没有做真正的接口权限控制页面显示，但是代码生成到你的项目了，你把返回menu的接口和希望权限控制的接口加点逻辑就可以了.下个版本把这个控制加入

**Comment by sunshine17123** [comment]
感谢，感谢
