### ISSUE TITLE
菜单路由

### ISSUE THREAD

**Issue by yaonv** [mtianyan/django-antd-tyadmin#14]
![image](https://user-images.githubusercontent.com/79888435/109591857-48414c00-7b49-11eb-8b79-29ea5733126b.png)
菜单路由如何和后端对接，动态生成

**Comment by mtianyan** [comment]
@yaonv route.js 中添加后，还需在sys/menu接口的返回值中添加。 你如果是新增model动态生成，不需要关注这个。会自动处理。

**Comment by haiya512** [comment]
> @yaonv route.js 中添加后，还需在sys/menu接口的返回值中添加。 你如果是新增model动态生成，不需要关注这个。会自动处理。

我新增了model， 为啥还是不能自动动态生成？
因为我自己编辑了admin.py文件？

**Comment by mtianyan** [comment]
查看项目README
3. 当项目新增了model，我该如何为新model生成前端页面+后端接口
+TY_ADMIN_CONFIG = {
+    'GEN_APPS': ['demo','new_app']
+}
如上GEN_APPS 中添加新app的name，然后运行下面命令

python manage.py gen_all && cd tyadmin && npm run build
