### ISSUE TITLE
DRF进行token认证时进行白名单放行问题？

### ISSUE THREAD

**Issue by sky508** [mtianyan/django-antd-tyadmin#15]
大佬，请问在进行REST_FRAMEWORK进行token验证时，怎么进行白名单放行呀，比如说:  "/api/vip/"开头的路径不进行token验证！

**Comment by mtianyan** [comment]
@sky508 这样路径对应的view 中    permission_classes = ()

**Comment by sky508** [comment]
> @sky508 这样路径对应的view 中 permission_classes = ()

只能在每个view里面加吗？有没有那种库可以在配置文件配的，就是配放行的url数组，然后这些url可以直接免token

**Comment by mtianyan** [comment]
这个你可以自己写一个中间件实现。
