### ISSUE TITLE
如果想无代码编辑出一个页面，请问需要学习哪些知识点？

### ISSUE THREAD

**Issue by Zyx-A** [mtianyan/django-antd-tyadmin#16]
如果想基于此框架无代码编辑出一个页面，具备基本的录入、展示功能，请问需要学习哪些知识点？
我看到 demo 中还可以自建栏目，但我搭建好之后，在 http://127.0.0.1:8000/xadmin 页面下，使用 superadmin 账户找遍了所有角落，都没有找到相应的入口。
在 http://127.0.0.1:8001/xadmin 端口的页面下，虽然找到了编辑的地方，但编辑后，怎么应用到主页面、怎么录入及展示数据，又是一头雾水。。。麻烦大佬指点。。。

**Comment by mtianyan** [comment]
@Zyx-A https://github.com/mtianyan/django-antd-tyadmin#3-%E5%BD%93%E9%A1%B9%E7%9B%AE%E6%96%B0%E5%A2%9E%E4%BA%86model%E6%88%91%E8%AF%A5%E5%A6%82%E4%BD%95%E4%B8%BA%E6%96%B0model%E7%94%9F%E6%88%90%E5%89%8D%E7%AB%AF%E9%A1%B5%E9%9D%A2%E5%90%8E%E7%AB%AF%E6%8E%A5%E5%8F%A3

**Comment by Zyx-A** [comment]
早就已经加过了，但我从始至终都没看到我所定义的项目的关键字。

**Comment by mtianyan** [comment]
@Zyx-A  加群发点截图看看呢
