### ISSUE TITLE
非常想知道Foreignkey如何生成前端下拉数据并显示的？

### ISSUE THREAD

**Issue by my9988** [mtianyan/django-antd-tyadmin#22]
![image](https://user-images.githubusercontent.com/17469220/119091357-8ce2d200-ba2a-11eb-9a3c-b51e4bafd2b4.png)
![image](https://user-images.githubusercontent.com/17469220/119091414-aab03700-ba2a-11eb-8196-5f28fb0560cb.png)

因为是前后端分离的设计，我没看到代码是如何实现后端为前端怎么生成数据的？我的做法是用api获取然后显示，当然这有点太麻烦，因为有太多这种需求，麻烦作者给我们讲下，谢谢！

**Comment by mtianyan** [comment]
外键类型的字段是api获取如 https://tyadmin.funpython.cn/api/xadmin/v1/demo_foreign_key?all=1 [{"id":8,"key":"8","ty_options_display_txt":"1-一级分类1"}] 
choice类型是直接生成到前端代码的。
