### ISSUE TITLE
为什么我项目跑起来，但是没有侧边栏，显示服务器异常。报"GET /api/xadmin/v1/sys/menu HTTP/1.1" 500 124494 和 dict' object has no attribute 'has_key'

### ISSUE THREAD

**Issue by kkkkf666** [mtianyan/django-antd-tyadmin#29]
http://127.0.0.1:8000/api/xadmin/v1/sys/menu
3.2.7
AttributeError
'dict' object has no attribute 'has_key'
/home/firefly/anaconda3/envs/tyadmin_api_cli/lib/python3.7/site-packages/demjson.py, line 911, in <listcomp>
/home/firefly/anaconda3/envs/tyadmin_api_cli/bin/python
3.7.11
['/media/firefly/000BD7B8000CDE06/tyadmin_api_cli/demos/tyadmin_demo_finish',  '/opt/ros/melodic/lib/python2.7/dist-packages',  '/home/firefly/anaconda3/envs/tyadmin_api_cli/lib/python37.zip',  '/home/firefly/anaconda3/envs/tyadmin_api_cli/lib/python3.7',  '/home/firefly/anaconda3/envs/tyadmin_api_cli/lib/python3.7/lib-dynload',  '/home/firefly/anaconda3/envs/tyadmin_api_cli/lib/python3.7/site-packages']

**Comment by mtianyan** [comment]
pip install demjson==2.2.4 -U

**Comment by mtianyan** [comment]
setuptools             57.5.0
