### ISSUE TITLE
验证码不显示图片

### ISSUE THREAD

**Issue by 8654321** [mtianyan/django-antd-tyadmin#32]
验证码显示英文字母Captcha

**Comment by mtianyan** [comment]
2. 图片没有正常显示
urls.py

from django.views.static import serve

urlpatterns = [
re_path('media/(?P<path>.*)', serve, {"document_root": settings.MEDIA_ROOT}),
]

也有可能是添加capture app 后 忘记再次migrate，导致capture包产生验证码失败。
