### ISSUE TITLE
requirements.txt中的依赖包和版本号可不可以写出来？

### ISSUE THREAD

**Issue by cnbillow** [mtianyan/django-antd-tyadmin#33]
django
djangorestframework
等
本地无法直接启动。

**Comment by mtianyan** [comment]
asgiref==3.5.0
demjson==2.2.4
Django==3.2.12
django-filter==21.1
django-ranged-response==0.2.0
django-simple-captcha==0.5.14
djangorestframework==3.13.1
mysqlclient==2.1.0
Pillow==9.0.1
pytz==2021.3
six==1.16.0
sqlparse==0.4.2
tyadmin-api-cli==0.8.1
typing_extensions==4.0.1

**Comment by mtianyan** [comment]
注意 setuptools版本             57.5.0
