### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by github3ape** [mtianyan/django-antd-tyadmin#36]
安装直接没成功。
error in demjson setup command: use_2to3 is invalid.
应该是需要将 setuptools 降级到 57.5.0版本，可是又会引起其他包的依赖错误：
celery 5.2.3 requires setuptools<59.7.0,>=59.1.1, but you have setuptools 57.5.0 which is incompatible.

**Comment by mtianyan** [comment]
项目中用到demjson的地方修改为demjson3即可

**Comment by mtianyan** [comment]
@github3ape 已发布0.8.2 版本修复该问题
